varReference:
- path: metadata/name
  kind: PipelineRun
- path: spec/params/value
  kind: PipelineRun
- path: spec/resources/name
  kind: PipelineRun
- path: spec/resources/resourceRef/name
  kind: PipelineRun
- path: spec/resources/name
  kind: Pipeline
- path: spec/tasks/resources/inputs/name
  kind: Pipeline
- path: spec/tasks/resources/inputs/resource
  kind: Pipeline
- path: spec/tasks/resources/outputs/name
  kind: Pipeline
- path: spec/tasks/resources/outputs/resource
  kind: Pipeline
- path: spec/tasks/params/value
  kind: Pipeline
- path: spec/inputs/resources/name
  kind: Task
- path: spec/outputs/resources/name
  kind: Task
- path: spec/steps/args
  kind: Task
- path: spec/params/value
  kind: PipelineResource
- path: metadata/name
  kind: PipelineResource
- path: metadata/namespace
  kind: PipelineRun
