apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../workspaces/frontend/manifests/kustomize/overlays/gateway-api

images:
  - name: ghcr.io/kubeflow/notebooks/workspaces-frontend
    newName: <REGISTRY>/workspaces-frontend
    newTag: <TAG>
