# permissions for end users to edit workspacekinds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: workspaces-controller
    app.kubernetes.io/managed-by: kustomize
  name: workspacekind-editor-role
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - workspacekinds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeflow.org
  resources:
  - workspacekinds/status
  verbs:
  - get
