apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspaces-backend
spec:
  replicas: 1
  selector:
    matchLabels: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels: {}
    spec:
      serviceAccountName: workspaces-backend
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 30
      containers:
      - name: workspaces-backend
        image: workspaces-backend
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        ports:
        - name: http-api
          containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /api/v1/healthcheck
            port: http-api
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /api/v1/healthcheck
            port: http-api
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1