apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workspaces-backend
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - workspaces
  - workspacekinds
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: workspaces-backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: workspaces-backend
subjects:
- kind: ServiceAccount
  name: workspaces-backend
  namespace: kubeflow-workspaces