apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backend-clusterrole
rules:
- apiGroups:
  - kubeflow.org
  resources:
  - workspaces
  - workspacekinds
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backend-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backend-clusterrole
subjects:
- kind: ServiceAccount
  name: nb-backend
  namespace: kubeflow-system