apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: dev-notebook-controller-culling
  namespace: istio-system
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/kube-system/sa/kube-proxy"]
  - to:
    - operation:
        methods:
        - GET
        paths:
        - '*/api/kernels'