apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspaces-controller
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: GATEWAY_NAME
          valueFrom:
            configMapKeyRef:
              name: kubeflow-workspaces-gateway-api-config
              key: GATEWAY_NAME
        - name: GATEWAY_HOSTS
          valueFrom:
            configMapKeyRef:
              name: kubeflow-workspaces-gateway-api-config
              key: GATEWAY_HOSTS
        - name: CLUSTER_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: kubeflow-workspaces-gateway-api-config
              key: CLUSTER_DOMAIN
        - name: EXTERNAL_AUTH_URL
          valueFrom:
            configMapKeyRef:
              name: kubeflow-workspaces-gateway-api-config
              key: EXTERNAL_AUTH_URL
        - name: WORKSPACE_NETWORK_POLICY_INGRESS
          valueFrom:
            configMapKeyRef:
              name: kubeflow-workspaces-gateway-api-config
              key: WORKSPACE_NETWORK_POLICY_INGRESS
        - name: WORKSPACE_NETWORK_POLICY_SELF
          valueFrom:
            configMapKeyRef:
              name: kubeflow-workspaces-gateway-api-config
              key: WORKSPACE_NETWORK_POLICY_SELF