apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- network-policy.yaml

patches:
- path: deployment_patch.yaml

configMapGenerator:
- name: kubeflow-workspaces-gateway-api-config
  envs:
  - params.env
