apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- http-route.yaml
- network-policy.yaml

labels:
- pairs:
    app.kubernetes.io/component: api

patches:
- path: deployment_patch.yaml
