apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: workspaces-backend
spec:
  podSelector:
    matchLabels:
      app: workspaces-backend
      app.kubernetes.io/component: api
  ingress:
    - from:
        ## allow traffic from the kubeflow namespace where the gateway proxy typically runs
        - namespaceSelector:
            matchExpressions:
              - key: kubernetes.io/metadata.name
                operator: In
                values:
                  - kubeflow
  policyTypes:
    - Ingress
