---
apiVersion: kubeflow.org/v1alpha1
kind: Notebook
metadata:
  name: notebook-sample-v1alpha1
spec:
  template:
    spec:
      containers:
        - name: notebook-sample-v1
          image: kubeflownotebookswg/jupyter:v1.5.0-rc.1
