---
apiVersion: kubeflow.org/v1beta1
kind: Notebook
metadata:
  name: notebook-sample-v1beta1
spec:
  template:
    spec:
      containers:
        - name: notebook-sample-v1
          image: public.ecr.aws/j1r0q0g6/notebooks/notebook-servers/jupyter:v1.5.0-rc.1
