# Notebook
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: notebook-kubeflow-user-test
  namespace: kubeflow-user
spec:
  gateways: 
  - kubeflow/kubeflow-gateway
  hosts:
  - 'kubeflow-user-notebook.kubeflow.example.org'
  http:
  - headers:
      request:
        remove: 
        - "Authorization"
        set: {}
    match:
    - uri:
        prefix: "/notebook/kubeflow-user/test/"
    rewrite:
      uri: "/notebook/kubeflow-user/test/"
    route:
    - destination:
        host: "test.kubeflow-user.svc.cluster.local"
        port: 
          number: 80
---
# Auth redirect
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: notebook-kubeflow-user-test-auth-redirect
  namespace: kubeflow-user
spec:
  gateways: 
  - kubeflow/kubeflow-gateway
  hosts:
  - 'kubeflow-user-notebook.kubeflow.example.org'
  http:
  - match:
    - uri:
        prefix: "/different-auth/"
    redirect:
      authority: "kubeflow.example.org"
      redirectCode: 307
---
# Redirect after auth
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: notebook-kubeflow-user-test-notebook-redirect
  namespace: kubeflow-user
spec:
  gateways: 
  - kubeflow/kubeflow-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: "/notebook/kubeflow-user/test/"
    redirect:
      authority: "kubeflow-user-notebook.kubeflow.example.org"
      redirectCode: 307