name: Python Linting

on:
  pull_request:
    branches:
      - main
      - v*-branch
      - notebooks-v1
    paths:
      - "**.py"

jobs:
  flake8-lint:
    runs-on: ubuntu-22.04
    name: Check
    steps:
      - name: Checkout source repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"

      - name: flake8 Lint
        uses: py-actions/flake8@84ec6726560b6d5bd68f2a5bed83d62b52bb50ba # v2
        with:
          exclude: "docs"