name: Semantic PRs

on:
  pull_request_target:
    types:
      - opened
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  validate_title:
    name: Validate Title
    runs-on: ubuntu-latest
    # only run on 'opened', or on 'edited' when the title itself changed
    if: github.event.action == 'opened' || github.event.changes.title != null
    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            fix
            feat
            improve
            refactor
            revert
            test
            ci
            docs
            chore

          # disallow all commit scopes
          disallowScopes: ".*"