name: "workspaces/controller: unit-tests"

permissions: {}

on:
  push:
    branches: [ "main", "notebooks-v2", "v*-branch" ]
  pull_request:
    paths: [ "workspaces/controller/**" ]
    branches: [ "main", "notebooks-v2", "v*-branch" ]

jobs:

  "unit-tests":
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: workspaces/controller/go.mod
          check-latest: true
          cache-dependency-path: workspaces/controller/go.sum

      - name: Test
        run: make test
        working-directory: workspaces/controller

  "e2e-tests":
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: helm/kind-action@v1
        with:
          version: v0.23.0
          node_image: kindest/node:v1.25.16@sha256:5da57dfc290ac3599e775e63b8b6c49c0c85d3fec771cd7d55b45fae14b38d3b
          cluster_name: kind

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: workspaces/controller/go.mod
          check-latest: true
          cache-dependency-path: workspaces/controller/go.sum

      - run: make test-e2e
        working-directory: workspaces/controller
